### ISSUE TITLE
Translated entities are not persisted

### ISSUE THREAD

**Issue by DjLeChuck** [umanit/translation-bundle#11]
[The documentation](https://github.com/umanit/translation-bundle#translate-your-entity) says: `The $translatedEntity will be persisted and flushed.`, but it's not true.

The automatic `persist` and `flush` are made in the `TranslatableCRUDController`, so if we do not use Sonata this will not work.

Maybe we should extract the main logic into a `trait`, so we can use it in the existing `TranslatableCRUDController` but also in a custom controller?

**Comment by artggd** [comment]
Sounds good to me. Go ahead 👍

**Comment by DjLeChuck** [comment]
I change my mind about this issue. Please refer to my PR: https://github.com/umanit/translation-bundle/pull/13
