### ISSUE TITLE
Improve `@EmptyOnTranslate()` annotation

### ISSUE THREAD

**Issue by DjLeChuck** [umanit/translation-bundle#12]
The `@EmptyOnTranslate()` set the field value as `NULL`. This is problematic if the field is not nullable.

I see two solution:
* set the value as empty string if the field is not nullable,
* make a new annotation `@DefaultOnTranslate("the value needed")`

**Comment by artggd** [comment]
Well, this raises more questions.

In both cases, what if the field is not a string? Should we make some sort of `DefaultValueSetter` and a `DefaultValueResolver` per field type? This sounds to me like a lot of work and I don't know if we would ever be able to cover all field types.

I reckon it would be easier to restrict the API and raise an exception when a field is marked as `@EmptyOnTranslate()` but is also non-nullable. Validation can do the rest when the user edits the translation.

I'm open to discussion though 🙂

**Comment by Peekmo** [comment]
I totally agree to raise an exception if an `@EmptyOnTranslate` is set but the field is not nullable, that makes no sense. The `@DefaultOnTranslate` is also a good idea as an improvement, but as an annotation, it will not be flexible enough without a lot of work as @artggd said, perhaps triggering an event once the translation is done is the easier thing to do to allow developers to do everything they want with their attributes ?

**Comment by DjLeChuck** [comment]
7f20e9d1c330de28faff9353da218cfcd9342743 An exception is now thrown if `@EmptyOnTranslate()` is used on non-nullable fields.
