### ISSUE TITLE
Trigger an event once the translation is done

### ISSUE THREAD

**Issue by DjLeChuck** [umanit/translation-bundle#15]
[...] perhaps triggering an event once the translation is done is the easier thing to do to allow developers to do everything they want with their attributes ?

_Originally posted by @Peekmo in https://github.com/umanit/translation-bundle/issues/12#issuecomment-493667493_

**Comment by artggd** [comment]
There is already two events raised before and after a translation is made, see [there](https://github.com/umanit/translation-bundle/blob/master/src/Event/TranslateEvent.php). From that event, you'll get the unpersisted, translated entity. This should be sufficient to change the default behaviour of any `@EmptyOnTranslate` field.

**Comment by DjLeChuck** [comment]
Indeed, thank you for the precision!
